### ISSUE TITLE
Bot should respond with "unknown command" if a command is unknown

### ISSUE THREAD

**Issue by jack828** [microadam/exso#20]
e.g. `@bot add to staging` -> `Unknown command "add to staging"`

I assume there is some limitations already in place where the bot ignores comments on repos that it is not enabled on?

**Comment by microadam** [comment]
Yeah it requires webhooks to be configured on the repo, so if its not enabled the bot won't respond. Unknown command would be useful, as currently it does just say nothing if it it doesn't know what to do
