### ISSUE TITLE
on-staging-partial label not removed

### ISSUE THREAD

**Issue by balaclark** [microadam/exso#5]
When a new release is marked as on staging and there was a previous `on-staging-partial` release labelled, the `on-staging-partial` label gets left behind when marking the new one.

![screen shot 2016-05-24 at 15 53 41](https://cloud.githubusercontent.com/assets/285598/15508542/cc3f2f80-21c7-11e6-8b76-feff1b8b74b1.png)

In the above screenshot the `on-staging-partial` label should not be there.

**Comment by microadam** [comment]
I believe this is fixed by this: https://github.com/microadam/exso/commit/a7214a4508e68cf6c6e81570897e09ac0712db89

Will close for now. Please re-open if you have the same issue again
